name: tinylearn_client
description: A new Flutter project.

publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  graphql_flutter: ^3.0.1
  provider: ^4.1.2
  shared_preferences: ^0.5.7+2
  intl: ^0.16.1
  cached_network_image: ^2.2.0+1
  package_info: ^0.4.1
  image_picker: ^0.6.7
  flutter_markdown: ^0.4.1
  url_launcher: ^5.4.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
